# Generated by Django 2.0.7 on 2019-11-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
