# Generated by Django 2.0.7 on 2019-12-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert_data', '0003_auto_20191130_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Location4_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
